name: Merge PR if membership validation succeeded
on:
  workflow_run:
    workflows:
      - Check Membership Pull Request
    types:
      - completed
jobs:
  merge-pr:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/pr.zip', Buffer.from(download.data));
      - run: unzip pr.zip
      - name: 'Merge PR'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.ORG_MANAGEMENT_TOKEN }}
          script: |
            var fs = require('fs');
            var pr_number = Number(fs.readFileSync('./NR'));
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number,
              merge_method: 'squash',
            });
