name: Merge PR if membership validation succeeded
on:
  workflow_run:
    workflows:
      - Check Membership Pull Request
    types:
      - completed
jobs:
  merge-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Merge PR
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          # Get the pull request number from the previous workflow's output
          PR_NUMBER=$(echo '${{ github.event.workflow_run.event.data.pull_requests[0].number }}')

          # Merge the pull request using the GitHub CLI
          gh pr merge $PR_NUMBER --auto
